In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[1.,-1.,2.],
            [2.,0.,0.],
            [0.,1.,-1.]])
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [3]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
# print(X_scaled[:1])
X_scaled.mean(axis=0) # axis 0 is columns and 1 is rows

array([0., 0., 0.])

In [5]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [7]:
scaler = preprocessing.StandardScaler()
scaler.fit(X) # it stores parameters in scaler object
scaled_output = scaler.transform(X)
scaled_output

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [32]:
data = [[0,3],[9,4],[2,7],[1,5]]
scaler1 = preprocessing.StandardScaler()
scaler1.fit(data) # it stores parameters in scaler object
scaled_output1 = scaler1.transform(data)
# sum of features on axis=0 will always be zero because it's centered around mean value of axis.
scaled_output1,scaled_output1.sum(),scaler1.mean_,scaled_output1.mean(axis=0)

(array([[-0.84852814, -1.18321596],
        [ 1.69705627, -0.50709255],
        [-0.28284271,  1.52127766],
        [-0.56568542,  0.16903085]]),
 2.220446049250313e-16,
 array([3.  , 4.75]),
 array([0.00000000e+00, 1.38777878e-17]))

In [19]:
X_test = np.array([[1,1,0]])
scaler.transform(X_test) # it uses the stored parameters during fit

array([[ 0.        ,  1.22474487, -0.26726124]])