In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[1.,-1.,2.],
            [2.,0.,0.],
            [0.,1.,-1.]])
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [6]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [20]:
# print(X_scaled[:1])
X_scaled.mean(axis=0) # axis 0 is columns and 1 is rows

array([0., 0., 0.])

In [16]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [17]:
scaler = preprocessing.StandardScaler()
scaler.fit(X) # it stores parameters in scaler object
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [19]:
X_test = np.array([[1,1,0]])
scaler.transform(X_test) # it uses the stored parameters during fit

array([[ 0.        ,  1.22474487, -0.26726124]])