In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [5]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[ 0.12334966],
        [-0.36975191]]),
 array([-0.29891989]))

In [6]:
# forward propagation without any hidden layer
for iter in range(1000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[2.61371925],
        [2.61254363]]),
 array([-4.04554462]),
 array([[0.01719918],
        [0.19263153],
        [0.19281443],
        [0.76507692]]))