In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T

In [3]:
X.shape,Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

In [6]:
# no hidden layer weights
weights = 2*np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights,bias

(array([[-0.63119354],
        [ 0.18897483]]),
 array([0.73795487]))

In [7]:
# forward propagation without any hidden layer
for iter in range(1000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)
    first_term = output - Y
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term

#     changes = np.array([[0.0],[0.0]])
#     for i in range(2):
#         for j in range(4):
#             changes[i][0] += first_two[j][0] * output0[j][i]
    changes = np.dot(output0.T,first_two)
    weights = weights - lr * changes
#     bias_change = 0.0
#     for j in range(4):
#         bias_change += first_two[j][0] * 1
    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change
output = sig(np.dot(X,weights)+bias)
print(weights)
print(bias)
print(output)

[[2.55442019]
 [2.55625033]]
[-3.96042283]
[[0.01869875]
 [0.19715483]
 [0.19686531]
 [0.75955616]]


# with hidden layer

In [8]:
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [9]:
output0 = X
outputHidden = sig(np.dot(output0,wh)+bh)
output = sig(np.dot(outputHidden,wo)+bo)
output

array([[0.51180258],
       [0.50226515],
       [0.53018924],
       [0.5211904 ]])