## Numpy 2D Array

In [5]:
!pip3 install requests

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 1.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 1.0 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 1.9 MB/s eta 0:00:00a 0:00:01


In [4]:
import numpy as np

list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(list)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
li=np.array([1,2,0,0,4,0])
index=np.where(li!=0)
for i in index[0]:
    print(i,end=' ')

0 1 4 

## NumPy 0s and 1s

In [2]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.zeros(10, dtype=int)
a[4] = 1

for e in a:
    print(e,end=' ')

0 0 0 0 1 0 0 0 0 0 

## NumPy Inclusive

In [3]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

a = np.arange(9,50)

for e in a:
    print(e, end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

## Identity Matrix

In [4]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.eye(5,6,dtype=int)

print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


## Cut the Rope

In [12]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.linspace(0,5,10)

for e in a[1:9]:
    print(round(e,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


## Print Elements

In [7]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

a = input_[2,:3]

for i in a:
    print(i, end=' ')
print()
b = input_[1:4,3]

for i in b:
    print(i, end=' ')
print()
c = input_[2:4]

for i in c:
    for j in i:
        print(j, end=' ')
print()
d = input_[1:3,1:3]

for i in d:
    for j in i:
        print(j, end=' ')
print()

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [24]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input_[2,0:3])
print(input_[1:4,3])
print(input_[2:,])
print(input_[1:3,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


## Non-Zero elements

In [8]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

arr = np.array([1,2,0,0,4,0])

ind = np.where(arr !=0)

for i in ind:
    for j in i:
        print(j, end=' ')

0 1 4 

## Multiples of 3

In [13]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

arr = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

ind = np.where(arr%3==0)
# print(ind)
for i in ind:
    for j in i:
        print(j, end=' ')

(array([1, 4, 7]),)
1 4 7 

## Odd elements

In [10]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a[a%2==1] = -1

for i in a:
    print(i, end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

## Replace Max

In [11]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])

a[a==a.max()] = 0

for e in a:
    print(e)

11
2
13
4
15
6
0
8
19


## Negate Elements

In [12]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a[(a>2) & (a <9)] = -a[(a>2) & (a <9)]

for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


## Height

In [13]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

a = age[height>155]
b = height[height>155]

for i in range(len(a)):
    print(a[i],end=' ')
    print(b[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [16]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
# ageFiltered=age[height>155]
# heightFiltered=height[height>155]
# for i in range(len(ageFiltered)):
#     print(ageFiltered[i],heightFiltered[i])

printage=np.where(height>155)
print(printage)
for i in printage[0]:
    print(age[i],height[i])


(array([ 0,  2,  3,  5, 10, 11, 13, 14, 16, 17, 18]),)
15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


## Sort by column
#Problem Statemnt:
#Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
#That means, we should re-arrange complete row based on 2nd columns' values.
#Given 2D array is:
# [[21 20 19 18 17]
 # [16 15 14 13 12]
  #[11 10  9  8  7]
  #[ 6  5  4  3  2]]
#Print the 2D array in sorted order.
#Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
#Output Format :
#[[ 6  5  4  3  2]
#[11 10  9  8  7]
#[16 15 14 13 12]
#[21 20 19 18 17]]


In [14]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

a = np.array([[21, 20, 19, 18, 17], [16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2,]])
print(a[a[:, 1].argsort()])


[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


## Killed in USA

In [15]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
import csv
file = open('terrorismData.csv')
data = csv.DictReader(file,skipinitialspace=True)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)
np_country = np.array(country)
bool_arr = np_country =='United States'

for i in np_killed[bool_arr]:
    print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


## Total Killed in USA

In [16]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
import csv
file = open('terrorismData.csv')
data = csv.DictReader(file,skipinitialspace=True)

killed = []
wounded = []
country = []

for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)
np_country = np.array(country)
bool_arr = np_country =='United States'

print(np_killed[bool_arr].sum())

3771


## Terrorism Day

In [17]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
import csv
file = open('terrorismData.csv')
data = csv.DictReader(file,skipinitialspace=True)

day = []

for row in data:
    day.append(row['Day'])

np_day = np.array(day)
# np_day[np_day==''] = '0.0'
np_day = np.array(np_day, dtype=float)
np_day = np.array(np_day, dtype=int)

print(len(np_day[(np_day>9)&(np_day<21)]))

66330


## Terrorism Date

In [15]:
import numpy as np
import csv
file = open('terrorismData.csv',encoding='ISO-8859-1')
data = csv.DictReader(file,skipinitialspace=True)

day = []
month = []
year = []
for row in data:
    day.append(row['Day'])
    month.append(row['Month'])
    year.append(row['Year'])

np_day = np.array(day)
np_day = np.array(np_day, dtype=float)
np_day = np.array(np_day, dtype=int)

np_month = np.array(month)
np_month = np.array(np_month, dtype=float)
np_month = np.array(np_month, dtype=int)

np_year = np.array(year)
np_year = np.array(np_year, dtype=float)
np_year = np.array(np_year, dtype=int)


np_year[np_year!=2010] = 0
np_year[np_month!=1] = 0
np_year[np_day==0] = 0

print(len(np_year[np_year!=0]))

271


In [16]:
import numpy as np
import csv

file_obj=open('terrorismData.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)
date=[]
for row in data:
    date.append(row['date'])
    
d=np.array(date)
d[d=='']='0'
d=np.array(d,dtype=float)
d=np.array(d,dtype=int)
da=d[(d>=10) & (d<=20)]
print(da.shape[0])

KeyError: 'date'

## Terror Casualty Attack

In [19]:
import csv
import numpy as np
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    country=[]
    kill=[]
    wound=[]
    group=[]
    for i in file_name:
        if (i["Year"]=="1999"):
            if (i["Country"]=="India" and i["State"]=="Jammu and Kashmir"):
                if (int(i["Month"])>=5 and int(i["Month"])<8):
                    if (int(i["Day"])>0):
                        country.append(i["City"])
                        group.append(i["Group"])
                        if i["Killed"]=="":
                            kill.append("0.0")
                        else:
                            kill.append(i["Killed"])
                        if i["Wounded"]=="":
                            wound.append("0.0")
                        else:
                            wound.append(i["Wounded"])
    country=np.array(country)
    kill=np.array(kill,dtype=float)
    wound=np.array(wound,dtype=float)
    group=np.array(group)
    kill=kill+wound
    l=np.argmax(kill)
    print(int(kill[l]),country[l],group[l])

22 Kargil District Separatists


In [41]:
import csv
import numpy as np
with open("terrorismData.csv", "r") as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace = True)
    casualty = []
    city = []
    for row in file_data:
        if row["Year"] == "1999" and (row["Month"] == "5" or row["Month"] == "6" or row["Month"] == "7"):
            if row["State"] == "Jammu and Kashmir":
                casualty.append((row["Killed"], row["Wounded"]))
                city.append((row["City"], row["Group"]))
    np_casualty = np.array(casualty)
    np_city = np.array(city)
    np_casualty[np_casualty == ""] = "0.0"
    np_casualty = np.array(np_casualty, dtype = 'float')
    np_casualty = np.sum(np_casualty, axis = 1)
    index = np.argmax(np_casualty)
    print(int(np_casualty[index]), np_city[index][0], np_city[index][1])

22 Kargil District Separatists


In [25]:
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np
file = open("terrorismData.csv")
filedata = csv.DictReader(file,skipinitialspace = True)
month = []
year = []
killed = []
wounded =[]
city = []
state = []
terroristgroup =[]
for row in filedata:
    month.append(row["Month"])
    year.append(row["Year"])
    killed.append(row["Killed"])
    wounded.append(row["Wounded"])
    city.append(row["City"])
    terroristgroup.append(row["Group"])
    state.append(row["State"])

killed_arr = np.array(killed)
wounded_arr = np.array(wounded)

killed_arr[killed_arr ==''] = '0.0'
wounded_arr[wounded_arr == ''] = '0.0'

killed_arr = np.array(killed_arr,dtype=float)
wounded_arr = np.array(wounded_arr,dtype=float)

np_month = np.array(month,dtype=int)
bool_arr = (np_month>=5) & (np_month<=7)

np_year = np.array(year,dtype=int)
bool_arr_year = (np_year==1999)

np_state = np.array(state)
bool_state = np_state=="Jammu and Kashmir"

reqd_kills = killed_arr[bool_arr&bool_arr_year]
reqd_wounded = wounded_arr[bool_arr&bool_arr_year]
casualities = killed_arr + wounded_arr
reqd_casualities = casualities[(bool_arr)&(bool_arr_year)&(bool_state)]
index= np.argmax(reqd_casualities)


max_casualities = int(np.max(reqd_casualities))
reqd_city = city[index]
group = terroristgroup[index]

print(max_casualities,reqd_city,group)

22 Unknown Unknown


## Terror Casualty Red

In [20]:
import csv
import numpy as np
killed=[]
wounded=[]
state=[]
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    for i in file_name:
        state.append(i['State'])
        killed.append(i['Killed'])
        wounded.append(i['Wounded'])

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)

np_wounded = np.array(wounded)
np_wounded[np_wounded==''] = '0.0'
np_wounded = np.array(np_wounded, dtype=float)
np_wounded = np.array(np_wounded, dtype=int)

np_casuality = np_wounded + np_killed
np_state = np.array(state)

print(np_casuality[(np_state=='Jharkhand') | (np_state=='Odisha') |(np_state=='Andhra Pradesh') | (np_state=='Chhattisgarh')].sum())


5628


## Terror City Casualty

In [21]:
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np
x={}
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    for i in file_name:
        if i['Country'] !='India'  or i['City']=='Unknown':
            continue
        killed_ = 0
        if i['Killed']!='':
            killed_ = int(float(i['Killed']))
        wounded_ = 0
        if i['Wounded']!='':
            wounded_ = int(float(i['Wounded']))
        causuality_ = killed_ + wounded_
        x[i['City']] = x.get(i['City'],0) + causuality_


y = {k: v for k, v in sorted(x.items(), key=lambda item: item[1], reverse=True)}
count = 0
for i in y:
    if count==5:
        break
    print(i, end=' ')
    print(y[i])
    count+=1


Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


In [10]:
import csv
import numpy as np

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    
    x={}
    for i in np_city:
        if i in x:
            x[np_city]+=np_casuality
        else:
            x[np_city]=np_casuality
y = {k: v for k, v in sorted(x.items(), key=lambda item: item[1], reverse=True)}
count = 0
for i in y:
    if count==5:
        break
    print(i, end=' ')
    print(y[i])
    count+=1


TypeError: unhashable type: 'numpy.ndarray'

## Terrorism FrequentDay

In [22]:
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np
x={}
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    for i in file_name:
        x[i['Day']] = x.get(i['Day'],0) + 1


y = {k: v for k, v in sorted(x.items(), key=lambda item: item[1], reverse=True)}
count = 0
for i in y:
    if count==1:
        break
    print(i, end=' ')
    print(y[i])
    count+=1


15 6500


In [2]:
from bs4 import BeautifulSoup
import requests

response = requests.get('https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt',verify=False)
data = BeautifulSoup(response.text, 'html.parser')

li = data.find_all(class_ = 'lister-item-header')
# p = data.find_all(class_ = 'genre')

# for i in li[0:3]:
#     print(i.a.string)

# for j in p[0:3]:
#     print(j.string.strip())

for i in li[:3]:
    print(i.h3.a.string,end=' ; ')
    for j in i.find_all(class_='genre'):
        print(j.string.strip(),end='')
    print("")


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.imdb.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


AttributeError: 'NoneType' object has no attribute 'a'

In [7]:
from bs4 import BeautifulSoup
import requests

response = requests.get('https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt',verify=False)
data = BeautifulSoup(response.text, 'html.parser')

li = data.find_all(class_ = 'lister-item-content')
# p = data.find_all(class_ = 'genre')

# for i in li[0:3]:
#     print(i.a.string)

# for j in p[0:3]:
#     print(j.string.strip())

for i in li[:3]:
    print(i.h3.a.string,end=' ; ')
    for j in i.find_all(class_='genre'):
        print(j.string.strip(),end='')
    print("")


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.imdb.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


Avengers: Infinity War ; Action, Adventure, Sci-Fi
Black Panther ; Action, Adventure, Sci-Fi
Deadpool 2 ; Action, Adventure, Comedy
