In [25]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[ 4 24 21 13  3 15]
 [20  8 27 14  6 10]
 [ 1 13 12 23  1 20]
 [ 7 21 28 17 15 29]
 [ 2  1 10 16 19 17]]


In [3]:
a > 20

array([[False, False, False,  True,  True, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False,  True, False,  True,  True, False],
       [False, False,  True, False, False,  True]])

In [8]:
a[a>20]

array([24, 25, 25, 25, 29, 27, 28, 27, 23, 28, 23, 24, 23, 23, 23])

In [26]:
b = a
print(b)

[[ 4 24 21 13  3 15]
 [20  8 27 14  6 10]
 [ 1 13 12 23  1 20]
 [ 7 21 28 17 15 29]
 [ 2  1 10 16 19 17]]


In [27]:
b[b>20] = 100
b

array([[  4, 100, 100,  13,   3,  15],
       [ 20,   8, 100,  14,   6,  10],
       [  1,  13,  12, 100,   1,  20],
       [  7, 100, 100,  17,  15, 100],
       [  2,   1,  10,  16,  19,  17]])

In [28]:
bool_arr = b[:,3] == 100
print(bool_arr)
b[bool_arr,3] = 98
b

[False False  True False False]


array([[  4, 100, 100,  13,   3,  15],
       [ 20,   8, 100,  14,   6,  10],
       [  1,  13,  12,  98,   1,  20],
       [  7, 100, 100,  17,  15, 100],
       [  2,   1,  10,  16,  19,  17]])

In [32]:
a = np.array([[21, 20, 19, 18, 17], [16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2,]])
print(a[a[:, 1].argsort()])
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


In [5]:
import numpy as np
import csv
file = open('terrorismData.csv',encoding='ISO-8859-1')
data = csv.DictReader(file,skipinitialspace=True)

killed = []
wounded = []
city = []
group = []
date = []
for row in data:
    date.append([row['Month'],row['Year']])
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    city.append(row['City'])
    group.append(row['Group'])

np_date = np.array(date,dtype=int)

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)

np_wounded = np.array(wounded)
np_wounded[np_wounded==''] = '0.0'
np_wounded = np.array(np_wounded, dtype=float)
np_wounded = np.array(np_wounded, dtype=int)

np_city = np.array(city)

np_group = np.array(group)

np_casuality = np_killed + np_wounded

# np_year[np_year!=1999] = 0
# np_year[(np_month!=5) & (np_month!=6) & (np_month!=7)] = 0

np_bool = (np_date[:,1]==1999) & ((np_date[:,0]==5) | (np_date[:,0]==6) | (np_date[:,0]==7))

np_city = np_city[np_bool]
np_casuality = np_casuality[np_bool]
np_group = np_group[np_bool]

for i in range(len(np_city)):
    print(np_casuality[i], end=' ')
    print(np_city[i],end=' ')
    print(np_group[i])

0 Cle Elum Unknown
13 Gaurigaon Maoists
0 Sejoud Unknown
0 Maryina Roshcha Unknown
0 Albuquerque Anti-Abortion extremists
2 Ghaiswang Maoists
2 Unknown Hezbollah
3 N'dalatando National Union for the Total Independence of Angola (UNITA)
5 Galashki Unknown
0 Huambo National Union for the Total Independence of Angola (UNITA)
8 Thiouarzedine Salafist Group for Preaching and Fighting (GSPC)
0 Huambo National Union for the Total Independence of Angola (UNITA)
1 Kafr Roummane Unknown
0 Huambo National Union for the Total Independence of Angola (UNITA)
0 Athens Unknown
2 Dhar al-Ramlah Hezbollah
0 Athens Unknown
0 Athens Unknown
7 Mur II Unknown
0 Piraeus November 17 Revolutionary Organization (N17RO)
0 Piraeus November 17 Revolutionary Organization (N17RO)
0 Piraeus November 17 Revolutionary Organization (N17RO)
2 Kadiria Unknown
5 Yuksekova District Unknown
3 Dadsara Hizbul Mujahideen (HM)
3 Kut Unknown
1 Belfast Loyalists
0 Sayyidat Mashmushah-al-Hariq Unknown
0 Athens Unknown
10 Port Loko 

In [15]:
import numpy as np
import csv

file = open('terrorismData.csv',encoding='ISO-8859-1')
data = csv.DictReader(file,skipinitialspace=True)


killed = []
wounded = []
city = []
group = []
date = []
for row in data:
    date.append([row['Month'],row['Year']])
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    city.append(row['City'])
    group.append(row['Group'])

    
np_date = np.array(date,dtype=int)

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)

np_wounded = np.array(wounded)
np_wounded[np_wounded==''] = '0.0'
np_wounded = np.array(np_wounded, dtype=float)
np_wounded = np.array(np_wounded, dtype=int)


np_city = np.array(city)

np_group = np.array(group)

np_casuality = np_killed + np_wounded


np_bool = (np_date[:,1]==1999) & ((np_date[:,0]==5) | (np_date[:,0]==6) | (np_date[:,0]==7))

print("hello")
# print(len(data))
print(len(np_bool[np_bool==True]))
print(len(np_wounded))

hello
435
181691


In [16]:
import csv
import numpy as np
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    country=[]
    kill=[]
    wound=[]
    group=[]
    for i in file_name:
        if (i["Year"]=="1999"):
            if (i["Country"]=="India" and i["State"]=="Jammu and Kashmir"):
                if (int(i["Month"])>=5 and int(i["Month"])<8):
                    if (int(i["Day"])>0):
                        country.append(i["City"])
                        group.append(i["Group"])
                        if i["Killed"]=="":
                            kill.append("0.0")
                        else:
                            kill.append(i["Killed"])
                        if i["Wounded"]=="":
                            wound.append("0.0")
                        else:
                            wound.append(i["Wounded"])
    country=np.array(country)
    kill=np.array(kill,dtype=float)
    wound=np.array(wound,dtype=float)
    group=np.array(group)
    kill=kill+wound
    l=np.argmax(kill)
    print(int(kill[l]),country[l],group[l])

22 Kargil District Separatists


In [27]:
import csv
import numpy as np
killed=[]
wounded=[]
state=[]
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    for i in file_name:
        state.append(i['State'])
        killed.append(i['Killed'])
        wounded.append(i['Wounded'])

np_killed = np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed, dtype=float)
np_killed = np.array(np_killed, dtype=int)

np_wounded = np.array(wounded)
np_wounded[np_wounded==''] = '0.0'
np_wounded = np.array(np_wounded, dtype=float)
np_wounded = np.array(np_wounded, dtype=int)

np_casuality = np_wounded + np_killed
np_state = np.array(state)

print(len(np_casuality[(np_state=='Jharkhand') | (np_state=='Odisha') |(np_state=='Andhra Pradesh') | (np_state=='Chhattisgarh')]))




2545


In [177]:
a = [3,200,4]
b = ['Jaipur','Bangalore','Delhi']
np_a = np.array(a)
np_b = np.array(b)
np_ab = np.vstack((np_a,np_b)).T
print(np_ab)
# print(ab[ab[:, 0].argsort()])
# print(ab[np.argsort(ab,axis=0)])
ab = [['3','Jaipur'],['200','Bangalore'],['4','Delhi']]
sorted(ab, key=lambda x: x[0], reverse=True)

# ab = ab[-ab[:, 0].argsort()]
# np.argsort(ab,0)
# ab

[['3' 'Jaipur']
 ['200' 'Bangalore']
 ['4' 'Delhi']]


[['4', 'Delhi'], ['3', 'Jaipur'], ['200', 'Bangalore']]

In [190]:
import csv
import numpy as np
x={}
with open("terrorismData.csv") as file_:
    file_name=csv.DictReader(file_)
    for i in file_name:
        if i['Country'] !='India' or i['City']=='Unknown':
            continue
        killed_ = 0
        if i['Killed']!='':
            killed_ = int(float(i['Killed']))
        wounded_ = 0
        if i['Wounded']!='':
            wounded_ = int(float(i['Wounded']))
        causuality_ = killed_ + wounded_
        x[i['City']] = x.get(i['City'],0) + causuality_


# dict(sorted(x.items(), key=lambda item: item[1]))
y = {k: v for k, v in sorted(x.items(), key=lambda item: item[1], reverse=True)}
count = 0
for i in y:
    if count==5:
        break
    print(i, end=' ')
    print(y[i])
    count+=1
# keys = []
# values = []
# for i in dict.keys():
#     keys.append(i)
#     values.append(dict[i])

# np_city = np.array(keys)
# np_causality = np.array(values,dtype=int)
# # print(np_casuality.sort())
# # print(np_casuality[-5:])
# # print(np_city)
# np_ans = np.vstack((np_city,np_causality)).T
# # print(np_ans)
# np_ans1 = np_ans[:5]
# print(np_ans1)
# np_ans1 = np_ans1[-np_ans1[:,1].argsort()]
# # np_ans.sort(axis=0)
# for i in np_ans1:
#     print(i)

# np_ans[-5:]
# for i in np_ans:
#     print(i)
# print(max(np_ans[:,1]))

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822
