In [1]:
import numpy as np

x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[1 1 5]
 [9 1 7]
 [6 4 5]]
[[6 1 8]
 [1 6 4]
 [8 9 7]]


In [3]:
ans = x - y
print(ans)

[[-5  0 -3]
 [ 8 -5  3]
 [-2 -5 -2]]


In [6]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,3)
print(x)
print(y)

[[9 6 1]
 [5 7 6]
 [3 6 4]]
[3 5 5]


In [7]:
ans = x - y
print(ans) # 1st row is auto replicated to all remaning rows

[[ 6  1 -4]
 [ 2  2  1]
 [ 0  1 -1]]


In [8]:
ans = y - x
print(ans)

[[-6 -1  4]
 [-2 -2 -1]
 [ 0 -1  1]]


In [9]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)

[[1 6]
 [2 9]
 [4 2]]
[[9 7 1]
 [7 6 1]]


In [11]:
y = np.transpose(y)
ans = y - x
print(ans)

[[ 8  1]
 [ 5 -3]
 [-3 -1]]


In [19]:
x = np.random.randint(1,10,(7,4))
y = np.random.randint(1,10,10)
print(x)
print(y)

[[3 7 6 1]
 [8 1 8 9]
 [8 3 1 3]
 [4 5 6 5]
 [4 1 6 4]
 [3 2 8 3]
 [6 7 3 5]]
[1 7 2 9 8 3 3 2 2 5]


In [24]:
z = y.reshape(2,5)
print(z)
print(y)

[[1 7 2 9 8]
 [3 3 2 2 5]]
[1 7 2 9 8 3 3 2 2 5]


In [29]:
y.resize(2,5)
print(y)

[[1 7 2 9 8]
 [3 3 2 2 5]]
