In [1]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [2]:
a = [1,2,3,'5','a',4.5]
b = np.array(a)
print(b)   # default behaviour is it will convert all to String if any one of them is as String

['1' '2' '3' '5' 'a' '4.5']


In [5]:
a = [1,2,3,'5','6',4.5]
b = np.array(a, dtype=float) # it will convert all the elements to the dtype argument passed
print(b)

[1.  2.  3.  5.  6.  4.5]


In [7]:
a = [1,2,4]
b = np.array(a*4)
b

array([1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4])

In [8]:
b = np.ones(3,dtype=int)
b

array([1, 1, 1])

In [10]:
b = np.zeros(3)
b # by default dtype is float

array([0., 0., 0.])

In [11]:
b = np.zeros(3, dtype=int)
b # by default dtype is float

array([0, 0, 0])

In [12]:
b = np.ones((3,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
b = np.zeros((3,5), dtype=int)
b # by default dtype is float

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
a = np.full(3,5)
a

array([5, 5, 5])

In [16]:
a = np.full((3,6),1) #dtype of this is by default as int
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
a = np.empty(4, dtype = int) # creates array with random int value
print(a)

[-8070450532247928832  2305851802688480763                    2
      562949953421312]


In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.arange(1, 20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
b = np.linspace(2,10) # by default the number of samples is 50, step values are chosen by function
print(b)
print(b[3]-b[2])
print(b[5]-b[4])

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [27]:
b = np.linspace(2,10,5, dtype=int)  # end point is included, number of samples provided is 5
print(b)

[ 2  4  6  8 10]


In [28]:
b = np.linspace(2,10,5, dtype=int, endpoint=False)  # end point is not included
print(b)

[2 3 5 6 8]


In [31]:
b = np.linspace(2,10,11, dtype=int, endpoint=False)  # end point is not included
print(b)

[2 2 3 4 4 5 6 7 7 8 9]


In [32]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
b = np.eye(3,4, dtype=int)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [36]:
b = np.random.rand(3)
b

array([0.91834353, 0.19632014, 0.3092715 ])

In [39]:
b = np.random.rand(10,4)
b

array([[0.5628996 , 0.57559352, 0.57636706, 0.13185041],
       [0.8013841 , 0.28080892, 0.14523208, 0.53473242],
       [0.2567106 , 0.41407768, 0.79904325, 0.29339575],
       [0.3406343 , 0.65456232, 0.31527401, 0.73549699],
       [0.88128322, 0.04349236, 0.34837212, 0.79024917],
       [0.51710513, 0.31926526, 0.9238209 , 0.03432694],
       [0.25934872, 0.14440657, 0.9457274 , 0.14802344],
       [0.08608587, 0.80586126, 0.69887796, 0.62669857],
       [0.56742807, 0.7978698 , 0.64636545, 0.88122951],
       [0.09951337, 0.31132425, 0.68320846, 0.9610918 ]])

In [37]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [38]:
np.random.rand() # one random value

0.8456445135088425

In [43]:
np.random.randint(10,size=(4,4)) # create integer random array of size 4,4 in the range 0 to 10

array([[9, 8, 9, 9],
       [0, 3, 3, 7],
       [7, 0, 9, 8],
       [2, 8, 4, 0]])

In [46]:
import numpy as np

a = np.linspace(0,5,10)

for e in a:
    print(round(e,2))

0.0
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.0
