In [1]:
import numpy as np
li = [1,2,3,4]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4]
[ 2 16 13 17  8]
[ 7 17  2 18  1]


In [2]:
li = [i+1 for i in li]
li

[2, 3, 4, 5]

In [3]:
a = a + 1 # numpy uses vectorization
a

array([ 3, 17, 14, 18,  9])

In [4]:
c = a + b
c

array([10, 34, 16, 36, 10])

In [5]:
d = a * b
d

array([ 21, 289,  28, 324,   9])

In [6]:
f = a - b
f

array([-4,  0, 12,  0,  8])

In [7]:
g = a//b
g

array([0, 1, 7, 1, 9])

In [8]:
h = a ** b
h

array([                2187, -2863221430593058543,                  196,
        -497033925936021504,                    9])

In [11]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

[ 3 17 14 18  9]
61
12.2
3
18
0
3


In [12]:
print(a)
print(b)

[ 3 17 14 18  9]
[ 7 17  2 18  1]


In [14]:
s = a > b
s

array([False, False,  True, False,  True])

In [16]:
a[2] = 0
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True False  True  True]
