In [1]:
import numpy as np

li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
print(arr.data) 
print(arr.shape)
print(arr.dtype)
print(arr.strides) # one integer is taking 8 bytes to move from one element to another element

(5,)
int64
(8,)


In [11]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [7]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d, dtype=int)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
print(arr_2d.data) 
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides) # (32,8) skip 32 bytes to move from one row to another row and
                        #8 bytes to skip one element to another in same row

(4, 4)
int64
(32, 8)


In [13]:
print(li_2d[2][3])
print(arr_2d[2][3])
print(arr_2d[2,3]) # it can be only done in numpy array

12
12
12


In [16]:
print(li_2d[2][:3])
print(arr_2d[2][1:3])


[10, 11]
[10 11]


In [17]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [18]:
print(arr_2d[0:3,2]) # this can be possible in numpy 

[ 3  7 11]


In [24]:
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a = input_[2,:3]
b = input_[1:4,3]
c = input_[2:4]
d = input_[1:3,1:3]
d

array([[ 7,  8],
       [12, 13]])