In [1]:
import numpy as np
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 2 14 19 13 13  6 17 17]


In [2]:
print(b>10)

[False  True  True  True  True False  True  True]


In [3]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr] # all the elements are filtered as per bool_arr condition
new_arr

[False  True  True  True  True False  True  True]


array([14, 19, 13, 13, 17, 17])

In [4]:
arr = b[b>10]
arr

array([14, 19, 13, 13, 17, 17])

In [8]:
arr = b[(b> 10) & (b<18)]
arr

array([14, 13, 13, 17, 17])

In [11]:
print(b)
c = b
c

[100 100 100  13  13   6 100 100]


array([100, 100, 100,  13,  13,   6, 100, 100])

In [12]:
c[:3] = 19
print(c)
c[c>15] = 100
c

[ 19  19  19  13  13   6 100 100]


array([100, 100, 100,  13,  13,   6, 100, 100])

In [13]:
print(b[b==100])

[100 100 100 100 100]


In [14]:
print(np.where(b==100))

(array([0, 1, 2, 6, 7]),)


In [15]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100  13  13   6 100 100]


In [17]:
ind = np.where(b==100)
print(ind)
print(a[ind])

(array([0, 1, 2, 6, 7]),)
['t' 'b' 'r' 'z' 'a']


In [18]:
print(a[np.where(b==100)])

['t' 'b' 'r' 'z' 'a']


In [19]:
arr = np.array([1,2,0,0,4,0])

ind = np.where(arr !=0)
ind

(array([0, 1, 4]),)

In [25]:
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
ind = a==a.max()
for i in ind:
    print(i)
print(ind)
# a[ind[0] = 0

# for e in a:
#     print(e)

False
False
False
False
False
False
True
False
False
[False False False False False False  True False False]


In [29]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

a = age[height>155]
b = height[height>155]

for i in range(len(a)):
    print(a[i],end=' ')
    print(b[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172
