In [8]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [2]:
iris = datasets.load_iris()

In [3]:
xtrain, xtest,ytrain,ytest = train_test_split(iris.data,iris.target,test_size=0.2)

In [15]:
clf = LinearRegression()
cross_val_score(clf,xtrain,ytrain,cv=KFold(n_splits=3,shuffle=True,random_state=0))

array([0.89028814, 0.91776807, 0.91221231])

In [21]:
clf = LinearRegression()
cross_val_score(clf,iris.data,iris.target)
# it gives the score 0 because iris data data is split in 3 sections 0-50 - class 1, 51-100 class2 and rest class3

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [20]:
clf = LinearRegression()
cross_val_score(clf,iris.data,iris.target,cv=KFold(n_splits=3,shuffle=True,random_state=0))

array([0.90322728, 0.92527008, 0.94214064])