In [5]:
import numpy as np
b = np.eye(5,6,dtype=int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [16]:
import requests
import json
h = {'User-Agent':'sumitdimshu','Authorization':'bearer ghu_6fiE8Zqa28jxTX2K2Tgf2FcaGdniWB3GiQU7'}
#r = requests.get('https://api.github.com/orgs/fossasia/repos',headers=h,verify=False)
#data = r.json()
#for i in data:
 #   print(i['name'])
page_num = 1
while True:
    p = {'type':'all','page':page_num}
    response = requests.get('https://api.github.com/orgs/fossasia/repos',headers = h,params = p,verify=False)
    x = response.json()
#     print(x)
    if len(x)==0:
        break
    else:
        page_num+=1
    for j in x:
        print(j['name'])  


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


x-mario
phimpme-android
phimpme-drupal
xmario_buildscript
pslab-case
meilix-systemlock
fossasia10-drupal
fossasia11-drupal
blog.fossasia.org
2010.fossasia.org
2014.fossasia.org
meilix
phimpme-wordpress
2015.fossasia.org
badge-magic-android
api.fossasia.net
directory.api.fossasia.net
common.api.fossasia.net
cmap.api.fossasia.net
feed.api.freifunk.net
feed.api.fossasia.net
fossasia-communities
sg18.sciencehack.asia
gci14.fossasia.org
fossasia-nodemailer
2011.fossasia.org
2012.fossasia.org
labs.fossasia.org
fossasia.net
foss.vn


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


libregraphics.asia
perspektive89.com
susi_smart_box
hotelxoai.com
yaydoc-artwork
fossasia-companion-android
loklak_webclient
circle-knitting
open-event-attendee-android
2018.fossasia.org
open-event
open-event-droidgen
open-event-wsgen
open-event-server
knitweb
knitpat
knitlib
pslab-expeyes
timeline.api.fossasia.net
2016.fossasia.org
fossasia.org
pslab-sister
pslab-test-jig
knitserver
sciencehack.asia
loklak_wok_android
gci15.fossasia.org
gci17.fossasia.org
flappy-svg
loklak-webtweets


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


loklak_tweetheatmap
unesco.sciencehack.asia
neurolab-hardware
loklak_movietweets
loklak_heatmap
fossasia-webfeeds
fossasia.github.io
jugaadfest.com
open-event-scraper
open-event-attendee-ios
fossasia-artwork
2017.fossasia.org
engelsystem
knittingpattern
CommonsNet
wp-tweets-widget
wp-recent-tweet
pslab-python
pslab-desktop
open-event-scripts
wp-tweet-feed-plugin
loklak_walls
wp-accesspress-twitter-feed
wp-rotatingtweets
wp-twitter-feeds
coc.fossasia.org
pslab-grove-shield
badgemagic.fossasia.org
2021.fossasia.org
2020.fossasia.org


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


kniteditor
badge-magic-ios
wp-juiz-last-tweet-widget
wp-twidget
wp-dev-buddy
loklak_tweetsearch_android
susi.ai
AYABInterface
susi_slackbot
sciencehack.in
loklak_wp_plugins
2018.codeheat.org
Xoai-Artwork
lxde-artwork
lubuntu-artwork
knitting.fossasia.org
KikiAuth
lxlauncher-vala
x-mario-center
events.fossasia.org
open-event-organizer-android
2013.fossasia.org
gci16.fossasia.org
susper-backbone
loklak_heatmapper
loklak_telegrambot
susi_server
codeheat.org
loklak_search
susi_fbbot


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


susi_telegrambot
susi_android
calendar.fossasia.org
sciencehack-artwork
susi_kikbot
susi_artwork
dev.susi.ai
fossbridge.com
searss
tofsims
mbdyn-gci
susi_tweetbot
query-server
green-park-2
susi_wechatbot
event-collect
loklak_EmojiTracker
geolocation
susi_desktop
support.eventyay.com
susper.com
visdom
susi_iOS
pslab-firmware
pslab-hardware
pslab-android
star-me
jobs.fossasia.org
susi_api_wrapper
open-event-frontend


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


susi_viberbot
susi_linux
asksusi
admin.susi.ai
open-event-theme
susi_skill_data
susi_skill_cms
yaydoc
susi_linebot
connfa-android
susi_skypebot
loklak_scraper_js
bbb-download
mew
loklak_publisher
meilix-generator
badgeyay
accounts.susi.ai
susi_gitterbot
giggity
giraffe
MMM-SUSI-AI
susi_alexa_skill
susi_cortana_skill
sphinx_fossasia_theme
open-event-next
susi_gassistantbot
loklak-timeline-plugin
pslab-webapp
susi_hangoutbot


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


sphinx_susiai_theme
phimpme-artwork
pslab-artwork
2016.codeheat.org
2017.codeheat.org
susi_chromebot
susi_firefoxbot
opendesign.asia
sciencetech.asia
sphinx_phimpme_theme
scrum_helper
open-event-legacy
meilix-artwork
pslab-bootloader
jugaadfest-artwork
neurolab-android
techcul.org
neurolab-firmware
open-event-organizer-ios
pslab-documentation
publiccode.asia
labyrinth
Flask_Simple_Form
Ember_Simple_Calculator
2019.fossasia.org
Connect-Me
dmca
meilix.org
flask-rest-jsonapi
susi_twitchbot


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


susi_zulipbot
snowboy
gci18.fossasia.org
pi-gen
jp.pslab.io
in.pslab.io
fossasia-jekyll-theme
fossasia.sg
eventyay-artwork
summit.fossasia.org
photos.fossasia.org
susi_installer
susi_python
susi_speech_server
FOSSASIA-Office
2019.codeheat.org
fossasia-presentations
orgmanager
hyderabad.jugaadfest.com
delhi.jugaadfest.com
speech_recognition
led-name-badge-ls32
Event-Safety-Measures
libsigrokdecode
libsigrok
eventyay.de
code.fossasia.org
ember-l10n
2020.codeheat.org
2022.fossasia.org


/Users/skumar6/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


In [19]:
int("149 min".split(" ")[0])

149

In [32]:
import numpy as np
a = np.linspace(0,5,10)
print(a)
for e in a[1:9]:
    print(round(e,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [ ]:
def isPrimeNum(n):
    